version: 2.1

jobs:
  test:
    docker: 
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run: go test

workflows:
  version: 2
  pre-merge-check:
    jobs:
      - test:
          filters:
            branches:
              ignore: main